openapi: 3.0.1
info:
  title: helloWorldAPI
  description: API Definition of helloWorldAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/hello/world
paths:
  /:
    get:
      responses:
        default:
          description: Default response
